version: 2
jobs:
  build:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
